#!/usr/bin/env python3
"""Reproducibly generate or verify the checked-in PackController CAN codecs."""

from __future__ import annotations

import argparse
import importlib.metadata
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


CANTOOLS_VERSION = "41.3.0"
GENERATED_FILES = ("pack_controller.c", "pack_controller.h")
GENERATOR_TIMESTAMP = re.compile(
    rf"(generated by cantools version {re.escape(CANTOOLS_VERSION)}) [^\r\n]+\."
)


def require_pinned_cantools() -> None:
    try:
        installed = importlib.metadata.version("cantools")
    except importlib.metadata.PackageNotFoundError:
        raise SystemExit(
            f"cantools=={CANTOOLS_VERSION} is required; "
            "install requirements-ci.txt"
        )

    if installed != CANTOOLS_VERSION:
        raise SystemExit(
            f"cantools=={CANTOOLS_VERSION} is required, found {installed}"
        )


def run_generator(repository: Path, output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "cantools",
            "generate_c_source",
            "--use-float",
            "--database-name",
            "pack_controller",
            "--output-directory",
            str(output),
            "can/pack_controller.dbc",
        ],
        cwd=repository,
        check=True,
    )

    for name in GENERATED_FILES:
        path = output / name
        content = path.read_text(encoding="utf-8")
        content, replacements = GENERATOR_TIMESTAMP.subn(
            r"\1 (timestamp normalized for reproducibility).", content
        )
        if replacements != 1:
            raise RuntimeError(f"unexpected cantools header in {path}")
        path.write_text(content, encoding="utf-8", newline="\n")


def check_generated(repository: Path, generated: Path) -> int:
    with tempfile.TemporaryDirectory(prefix="packcontroller-dbc-") as temp:
        candidate = Path(temp)
        run_generator(repository, candidate)
        drift = []
        for name in GENERATED_FILES:
            checked_in = generated / name
            regenerated = candidate / name
            if not checked_in.is_file() or checked_in.read_bytes() != regenerated.read_bytes():
                drift.append(name)

    if drift:
        print("generated CAN codec drift detected: " + ", ".join(drift))
        print("run: python tools/generate_dbc.py")
        return 1

    print(f"OK: generated CAN codecs match cantools=={CANTOOLS_VERSION}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare regenerated output with generated/can instead of updating it",
    )
    args = parser.parse_args()

    require_pinned_cantools()
    repository = Path(__file__).resolve().parents[1]
    generated = repository / "generated" / "can"

    if args.check:
        return check_generated(repository, generated)

    with tempfile.TemporaryDirectory(prefix="packcontroller-dbc-") as temp:
        candidate = Path(temp)
        run_generator(repository, candidate)
        generated.mkdir(parents=True, exist_ok=True)
        for name in GENERATED_FILES:
            shutil.copyfile(candidate / name, generated / name)

    print(f"Generated {', '.join(GENERATED_FILES)} with cantools=={CANTOOLS_VERSION}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
